apiVersion: ray.io/v1
kind: RayCluster
metadata:
  labels:
{{ include "ray-cluster.labels" . | indent 4 }}
  name: {{ include "ray-cluster.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{ with .Values.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{ end }}
spec:
  {{- with .Values.head.rayVersion }}
  rayVersion: {{ . }}
  {{- end }}
  {{- with .Values.head.enableInTreeAutoscaling }}
  enableInTreeAutoscaling: {{ . }}
  {{- end }}
  {{- with .Values.head.autoscalerOptions }}
  autoscalerOptions: {{- toYaml . | nindent 4 }}
  {{- end }}
  headGroupSpec:
    {{- with .Values.head.headService }}
    headService: {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.service.type }}
    serviceType: {{ . }}
    {{- end }}
    rayStartParams:
    {{- if and (not .Values.head.rayStartParams) (not .Values.head.initArgs) }}
      {}
    {{- else }}
      {{- range $key, $val := .Values.head.rayStartParams }}
        {{ $key }}: {{ $val | quote }}
      {{- end }}
      {{- /*
      initArgs is a deprecated alias for rayStartParams.
      */}}
      {{- range $key, $val := .Values.head.initArgs }}
        {{ $key }}: {{ $val | quote }}
      {{- end }}
    {{- end }}
    template:
      spec:
        {{- with .Values.head.dnsConfig }}
        dnsConfig: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.imagePullSecrets }}
        imagePullSecrets: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.head.serviceAccountName }}
        serviceAccountName: {{ . }}
        {{- end }}
        {{- with .Values.head.restartPolicy }}
        restartPolicy: {{ . }}
        {{- end }}
        {{- with .Values.head.initContainers }}
        initContainers: {{- toYaml . | nindent 10 }}
        {{- end }}
        containers:
          - {{ with .Values.head.volumeMounts }}
            volumeMounts: {{- toYaml . | nindent 12 }}
            {{- end }}
            name: ray-head
            {{- if .Values.head.image }}
            image: {{ .Values.head.image.repository }}:{{ .Values.head.image.tag }}
            imagePullPolicy: {{ .Values.head.image.pullPolicy }}
            {{- else }}
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            {{- end }}
            {{- with .Values.head.resources }}
            resources: {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .Values.head.securityContext }}
            securityContext:
            {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with concat .Values.common.containerEnv .Values.head.containerEnv }}
            env:
            {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .Values.head.envFrom }}
            envFrom: {{- toYaml . | nindent 14}}
            {{- end }}
            {{- with .Values.head.ports }}
            ports: {{- toYaml . | nindent 14}}
            {{- end }}
            {{- with .Values.head.lifecycle }}
            lifecycle:
            {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .Values.head.command }}
            command: {{- toYaml . | nindent 14}}
            {{- end }}
            {{- with .Values.head.args }}
            args: {{- toYaml . | nindent 14}}
            {{- end }}
          {{- with .Values.head.sidecarContainers }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        {{ with .Values.head.volumes }}
        volumes: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.head.topologySpreadConstraints }}
        topologySpreadConstraints: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.head.affinity }}
        affinity: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{ with .Values.head.priorityClassName }}
        priorityClassName: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{ with .Values.head.priority }}
        priority: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.head.tolerations }}
        tolerations: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.head.nodeSelector }}
        nodeSelector: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.head.podSecurityContext }}
        securityContext:
        {{- toYaml . | nindent 10 }}
        {{- end }}
      metadata:
        {{- with .Values.head.annotations }}
        annotations: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.head.labels }}
        labels: {{- toYaml .Values.head.labels | nindent 10 }}
{{ include "ray-cluster.labels" . | indent 10 }}
        {{ else }}
        labels: {{ include "ray-cluster.labels" . | nindent 10 }}
        {{- end }}

  workerGroupSpecs:
  {{- range $groupName, $values := .Values.additionalWorkerGroups }}
  {{- if ne $values.disabled true }}
  - rayStartParams:
    {{- if and (not $values.rayStartParams) (not $values.initArgs) }}
      {}
    {{- else }}
      {{- range $key, $val := $values.rayStartParams }}
        {{ $key }}: {{ $val | quote }}
      {{- end }}
      {{- /*
      initArgs is a deprecated alias for rayStartParams.
      */}}
      {{- range $key, $val := $values.initArgs }}
        {{ $key }}: {{ $val | quote }}
      {{- end }}
    {{- end }}
    replicas: {{ $values.replicas }}
    minReplicas: {{ $values.minReplicas | default 0 }}
    maxReplicas: {{ $values.maxReplicas | default 2147483647 }}
    numOfHosts: {{ $values.numOfHosts | default 1 }}
    groupName: {{ $groupName }}
    template:
      spec:
        {{- with $values.dnsConfig }}
        dnsConfig: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with $.Values.imagePullSecrets }}
        imagePullSecrets: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with $values.serviceAccountName }}
        serviceAccountName: {{ . }}
        {{- end }}
        {{- with $values.restartPolicy }}
        restartPolicy: {{ . }}
        {{- end }}
        {{- with $values.initContainers }}
        initContainers: {{- toYaml . | nindent 10 }}
        {{- end }}
        containers:
          - {{ with $values.volumeMounts }}
            volumeMounts: {{- toYaml . | nindent 12 }}
            {{- end }}
            name: ray-worker
            {{- if $values.image }}
            image: {{ $values.image.repository }}:{{ $values.image.tag }}
            imagePullPolicy: {{ $values.image.pullPolicy }}
            {{- else }}
            image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
            imagePullPolicy: {{ $.Values.image.pullPolicy }}
            {{- end }}
            {{- with $values.resources }}
            resources: {{- toYaml . | nindent 14 }}
            {{- end }}
            securityContext:
            {{- toYaml $values.securityContext | nindent 14 }}
            {{- with concat $.Values.common.containerEnv ($values.containerEnv | default list) }}
            env:
            {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with $values.envFrom }}
            envFrom: {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with $values.ports }}
            ports: {{- toYaml . | nindent 14}}
            {{- end }}
            {{- with $values.lifecycle }}
            lifecycle:
            {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with $values.command }}
            command: {{- toYaml . | nindent 14}}
            {{- end }}
            {{- with $values.args }}
            args: {{- toYaml . | nindent 14}}
            {{- end }}
          {{- with $values.sidecarContainers }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        {{ with $values.volumes }}
        volumes: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with $values.topologySpreadConstraints }}
        topologySpreadConstraints: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with $values.affinity }}
        affinity: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{ with $values.priorityClassName }}
        priorityClassName: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{ with $values.priority }}
        priority: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with $values.tolerations }}
        tolerations: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with $values.nodeSelector }}
        nodeSelector: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with $values.podSecurityContext }}
        securityContext:
        {{- toYaml . | nindent 10 }}
        {{- end }}
      metadata:
        {{- with $values.annotations }}
        annotations: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if $values.labels }}
        labels: {{- toYaml $values.labels | nindent 10 }}
{{ include "ray-cluster.labels" $ | indent 10 }}
        {{ else }}
        labels: {{ include "ray-cluster.labels" $ | nindent 10 }}
        {{- end }}

  {{- end }}
  {{- end }}
  {{- if ne (.Values.worker.disabled | default false) true }}
  - rayStartParams:
    {{- if and (not .Values.worker.rayStartParams) (not .Values.worker.initArgs) }}
      {}
    {{- else }}
      {{- range $key, $val := .Values.worker.rayStartParams }}
        {{ $key }}: {{ $val | quote }}
      {{- end }}
      {{- /*
      initArgs is a deprecated alias for rayStartParams.
      */}}
      {{- range $key, $val := .Values.worker.initArgs }}
        {{ $key }}: {{ $val | quote }}
      {{- end }}
    {{- end }}
    replicas: {{ .Values.worker.replicas }}
    minReplicas: {{ .Values.worker.minReplicas | default 0 }}
    maxReplicas: {{ .Values.worker.maxReplicas | default 2147483647 }}
    numOfHosts: {{ .Values.worker.numOfHosts | default 1 }}
    groupName: {{ .Values.worker.groupName }}
    template:
      spec:
        {{- with .Values.worker.dnsConfig }}
        dnsConfig: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.imagePullSecrets }}
        imagePullSecrets: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.worker.serviceAccountName }}
        serviceAccountName: {{ . }}
        {{- end }}
        {{- with .Values.worker.restartPolicy }}
        restartPolicy: {{ . }}
        {{- end }}
        {{- with .Values.worker.initContainers }}
        initContainers: {{- toYaml . | nindent 10 }}
        {{- end }}
        containers:
          - {{ with .Values.worker.volumeMounts }}
            volumeMounts: {{- toYaml . | nindent 12 }}
            {{- end }}
            name: ray-worker
            {{- if .Values.worker.image }}
            image: {{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}
            imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
            {{- else }}
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            {{- end }}
            resources: {{- toYaml .Values.worker.resources | nindent 14 }}
            {{- with .Values.worker.securityContext }}
            securityContext:
            {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with concat .Values.common.containerEnv .Values.worker.containerEnv }}
            env:
            {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .Values.worker.envFrom }}
            envFrom: {{- toYaml . | nindent 14}}
            {{- end }}
            {{- with .Values.worker.ports }}
            ports: {{- toYaml . | nindent 14}}
            {{- end }}
            {{- with .Values.worker.lifecycle }}
            lifecycle:
            {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .Values.worker.command }}
            command: {{- toYaml . | nindent 14}}
            {{- end }}
            {{- with .Values.worker.args }}
            args: {{- toYaml . | nindent 14}}
            {{- end }}
          {{- with .Values.worker.sidecarContainers }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        {{ with .Values.worker.volumes }}
        volumes: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.worker.affinity }}
        affinity: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{ with .Values.worker.priorityClassName }}
        priorityClassName: {{ . }}
        {{- end }}
        {{ with .Values.worker.priority }}
        priority: {{ . }}
        {{- end }}
        {{- with .Values.worker.tolerations }}
        tolerations: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.worker.nodeSelector }}
        nodeSelector: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.worker.topologySpreadConstraints }}
        topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.worker.podSecurityContext}}
        securityContext:
        {{- toYaml . | nindent 10 }}
        {{- end }}
      metadata:
        {{- with .Values.worker.annotations }}
        annotations: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.worker.labels }}
        labels: {{- toYaml .Values.worker.labels | nindent 10 }}
{{ include "ray-cluster.labels" . | indent 10 }}
        {{ else }}
        labels: {{ include "ray-cluster.labels" $ | nindent 10 }}
        {{- end }}
  {{- end }}
